baseURL = 'https://har79.com/'
languageCode = 'en'
title = 'har79'
titleCaseStyle = 'firstupper'
[params]
  author = "Harry Cameron"
  description = "TODO"
[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "node_modules/@fortawesome/fontawesome-free/svgs"
    target = "assets/icons"
  [[module.mounts]]
    source = "node_modules/@har79/dice-app/dist"
    target = "static/dice"
