# Site settings
title: har79
description: >
  Description
url: "https://har79.github.io"
baseurl: ""
repo: "https://github.com/har79/har79.github.io"
exclude: ['README.md']

# Build settings
markdown: kramdown
sass:
  style: compressed